Hometask 3
AsakoKabe/tank-software-design pull request #3
Opened 2023-10-01 10:32 UTC by AsakoKabe

<img width="722" alt="image" src="https://github.com/AsakoKabe/tank-software-design/assets/81520942/771403e7-a436-46f2-b8e9-d648c1bf0961">

2023-10-01 12:51 UTC, iagoshkov requested changes

2023-10-01 12:51 UTC, iagoshkov commented on src/main/java/ru/mipt/bit/platformer/GameDesktopLauncher.java
> +    private Obstacle obstacle;
Зачем нужны поля tank, obstacle, tankGraphics, obstacleGraphics?

2023-10-01 12:51 UTC, iagoshkov commented on src/main/java/ru/mipt/bit/platformer/action/ActionController.java
> +        return validateMoveAction(gameEntity, (Move) action);
Здесь просто супер нарушение OCP и SRP.

2023-10-01 12:51 UTC, iagoshkov commented on src/main/java/ru/mipt/bit/platformer/action/InputController.java
> +    public void initKeyBoardMappings() {
Конкретные значения обычно не зашивают в класс внутри метода этого класса. Нарушает OCP.

2023-10-01 12:51 UTC, iagoshkov commented on src/main/java/ru/mipt/bit/platformer/gameEntities/GameEntity.java
> +public interface GameEntity {
А если я захочу добавить стрельбу? мне ее тоже в этот интерфейс выносить? а как тогда быть с объектами, которые не могут стрелять?

2023-10-01 12:51 UTC, iagoshkov commented on src/main/java/ru/mipt/bit/platformer/gameEntities/Obstacle.java
> +public class Obstacle implements GameEntity{
Вот у вас препятствие настолько не вписывается в ваш интерфейс GameEntity, что аж целых два метода пустых из интерфейса. Это верный знак, что с интерфейсом что-то не так.

2023-10-01 12:51 UTC, iagoshkov commented on src/main/java/ru/mipt/bit/platformer/graphics/EntityGraphics.java
> +    public void update(TileMovement tileMovement);
А зачем нам в интерфейсе метод update?
Почему не оставить просто draw() и все?
А там уже каждая реализация внутри себя решает как именно рисовать. Если ей нужно что-то обновить/пересчитать перед отрисовкой – она это сделает.

2023-10-01 12:51 UTC, iagoshkov commented on src/main/java/ru/mipt/bit/test/LevelTest.java
> +    void testUpdateStateTankFinishedMovementCollidesCreated() {
Мы что именно хотим проверить в этом методе? логику столкновений? или то, как у нас работает метод level.updateState?

2023-10-01 12:51 UTC, iagoshkov commented on src/main/java/ru/mipt/bit/platformer/action/Move.java
> +        this.coordinates = coordinates;
Если у нас тут coordinates и rotation – это вектор куда надо сместиться, то зачем они нам тут разделные? У нас для этого есть абстракция Direction.
А тут получается можно в конструктор передать вектор coordinates неконсистентный с rotation

2023-10-01 12:51 UTC, iagoshkov commented on src/main/java/ru/mipt/bit/test/MoveFactoryTest.java
> +        for (Direction direction: Direction.values()){
В таких случаях можно даже for не писать, а использовать "параметризованный тест"

2023-10-01 12:51 UTC, iagoshkov commented on src/main/java/ru/mipt/bit/test/ObstacleTest.java
> +    void dontMoving() {
Это конечно суперстранно выглядит, у сущности есть метод moveTo и мы в тесте проверяем, что она никуда не двигается при вызове этого метода )))

2023-10-01 12:51 UTC, iagoshkov commented on src/main/java/ru/mipt/bit/test/TankTest.java
> +        tank.moveTo(Direction.UP.getCoordinates(), Direction.UP.getRotation());
Зачем передавать два поля из объекта Direction?
Проще сразу передать туда целиком объект Direction, одним параметром.

2023-10-01 12:51 UTC, iagoshkov commented on src/main/java/ru/mipt/bit/test/TankTest.java
> +class TankTest {
Я думаю мы эти тесты разберем на занятии, тут очень много что нужно сказать, я это все не напишу )

2023-10-01 18:00 UTC, AsakoKabe commented on src/main/java/ru/mipt/bit/test/LevelTest.java
> +    void testUpdateStateTankFinishedMovementCollidesCreated() {
Здесь у меня получилась ситуация, о которой я спрашивал в телеграмме. Я могу вызвать `level.updateState()`, но как мне тогда проверить, что метод корректно отработал? 
Так как метод `updateState()` изменяет состояние `GameEntity`, я решил это проверить на примере внутреннего состояния танка (`destinationCoordinates` установились в `currentCoordinates` у танка). Возможно тогда следовало просто проверить изменение координат у танка, а не коллизию?

2023-10-01 18:02 UTC, AsakoKabe commented on src/main/java/ru/mipt/bit/test/TankTest.java
> +class TankTest {
Я только за) Можете всегда брать мой код для разбора)

2023-10-01 18:07 UTC, iagoshkov commented on src/main/java/ru/mipt/bit/test/LevelTest.java
> +    void testUpdateStateTankFinishedMovementCollidesCreated() {
Ну а какой "контракт" у level.update?
Он должен позвать update у всех сущностей которые туда добавлены, верно?
Значит надо добавить туда сущностей и проверить, что у них позвали "update".
Необязательно "настоящих" сущностей, можно в тесте сделать реализацию GameEntity, которая просто будет проверять позвали ли у нее update или нет.
Специально для этого в экосистеме jUnit (в mockito) есть понятие mock-ов, которые все эти проверки упрощают в одну строку кода.
Погуглите по словам "junit mock verify method was called"

2023-10-01 18:12 UTC, AsakoKabe commented on src/main/java/ru/mipt/bit/platformer/action/ActionController.java
> +        return validateMoveAction(gameEntity, (Move) action);
Для меня при рефакторинге это был самый главный камень преткновения. Я не знал как лучше это реализовать. Проблема была в том, что нам надо как-то валидировать `Action`, например на наличие коллизией. Но в текущей логике мы не просто исключаем этот `Action`, а применяем его избранно (например, для танка при наличии коллизии координаты не применяет, а rotation - да). 
Была идея создать `ActionValidator`, но возникали вопросы по типа, а где его хранить, как вызывать, а для разных `Action` у нас должна быть разная валидация и т.д., поэтому решил оставить на текущий момент валидацию внутри `Action`

2023-10-01 18:15 UTC, iagoshkov commented on src/main/java/ru/mipt/bit/platformer/action/ActionController.java
> +        return validateMoveAction(gameEntity, (Move) action);
Ну тот все просто – если какие то действия у вас  специфичные для типа Action-а, то это знание нужно туда и поместить (инкаспулировать).
Что-то в MoveAction, что-то в ShootAction.

2023-10-01 18:44 UTC, AsakoKabe commented on src/main/java/ru/mipt/bit/platformer/action/ActionController.java
> +        return validateMoveAction(gameEntity, (Move) action);
Это у меня есть. Если была обнаружена коллизия, то при вызове `apply()` у `Action` у объекта изменится только `rotation`. 

1. Проблема тогда в том, что в `action.apply()` у меня передается `GameEntity`? А как иначе у меня `Action` выполнит изменения над `GameEntity`? Только если при создании `Action` в конструктор передавать `GameEntity`. Но идея хранить в каждом `Action` `GameEntity` выглядит нарушением OCP в еще большей мере.

2. Передача GameEntity и Action в функцию валидации тоже нарушение OCP. Но когда тогда мы можем провалидировать Action. 

а) Хранить логику внутри `Action`? Но получается тогда для валидации `MoveAction` нам надо внутри него знать о состояние всех элементов на `level`?
b) Валидировать на уровне `Level`? Но он у нас никак не связан с `Action`. 
c) Создавать внешний класс `ActionValidator`, в котором будет хранится `level`, а в `ActionController` положим этот валидатор и будем через него валидировать все `Action`? 

Вариант c мне нравится больше всего, но казалось, что слишком много классов получается и в этом легко запутаться, но нарисовал диаграмму и кажется не так уж и плохо. Что думаете?


<img width="561" alt="image" src="https://github.com/AsakoKabe/tank-software-design/assets/81520942/606e5d65-6628-4850-8c3f-d09ea4a425ec">

2023-10-01 19:43 UTC, iagoshkov commented on src/main/java/ru/mipt/bit/platformer/action/ActionController.java
> +        return validateMoveAction(gameEntity, (Move) action);
Ну как я уже и писал – можно просто логически рассуждать. В вашей терминологии – кто лучше самого Action-а знает как его "валидировать"? Никто. Для каждого Action-а там своя логика будет.
Значит она должна вызываться из самого Action-а и быть инкапсулирована в нем (сейчас она у вас размазана – частично в ActionController-е – вы там "взводите флаг" resetCoordinates, который потом проверяете уже в самом apply в MoveAction – это очень сложно понимать и менять).
Дальше смотрим - нужно ли прям внутри Action-а реализовывать код, который будет проверять коллизии и знать обо всех объектах – наверно нет, потому что это может нарушать SRP и потому что логика проверки коллизии может потребоваться и вне Action-а (в тестах или где-то еще при размещении рандомных объектов на карте, например). Т.е. логика проверки коллизий - хорошая и переиспользуемая абстракция.
Значит просто Action-у нужен какой-то внешний сервис, который сможет проверить коллизии. И который будет каким-то образом в Action передаваться, например через конструктор.
Например, какой-нибудь интерфейс CollisionDetector.
А реализацией CollisionDetector-а может быть либо отдельный сервис, либо, может быть и сам Level.

2023-10-01 19:46 UTC, iagoshkov commented on src/main/java/ru/mipt/bit/platformer/action/ActionController.java
> +        return validateMoveAction(gameEntity, (Move) action);
Вынести логику валидации Action-а в какой-то внешний сервис наврядли получится, т.к. этой логике валидации нужно много знать про сам Action и, возможно, про объект над которым он применяется.
Поэтому лучше всего инкапсулировать эту логику в конкретном Action-е.

2023-10-02 16:19 UTC, AsakoKabe commented on src/main/java/ru/mipt/bit/platformer/gameEntities/Obstacle.java
> +    public void updateState(float deltaTime) {
Я оставил update() у Obstacle, потому что по сути это один из главных методов у GameEntity, то что он не выполняется у Obstacle - это скорее всего редко исключение(вообще никак не изменяется).

2023-10-02 16:19 UTC, AsakoKabe commented on src/main/java/ru/mipt/bit/platformer/action/MoveAction.java
> +        Movable movableGameEntity = (Movable) gameEntity;
Нормальная ли практика кастовать объекты?

2023-10-02 16:19 UTC, AsakoKabe commented on src/main/java/ru/mipt/bit/platformer/gameEntities/Level.java
> +    public boolean collidesExist(GridPoint2 coordinates) {
Не создаю отдельные объект для детекции коллизии, потому что для его работы потребуется передавать в него один из главных атрибутов Level. Это ли не очень грубое нарушение инкапсуляции?

2023-10-08 11:44 UTC, iagoshkov approved these changes
Можно мержить, есть некоторые огрехи, но в целом сойдет

2023-10-08 11:44 UTC, iagoshkov commented on src/main/java/ru/mipt/bit/platformer/GameDesktopLauncher.java
> +        HashMap<GameEntity, Action> actions = actionController.generateGameEntitiesActions();
Тут немного не OCP – а как генерировать Action-ы из AI? А не с кнопок.

2023-10-08 11:44 UTC, iagoshkov commented on src/main/java/ru/mipt/bit/platformer/action/InputController.java
> +        gameEntities.add(gameEntity);
Непонятно, а зачем так?
Мы что захотим когда-то управлять с кнопок сразу несколькими объектами?
Типа нажали "вверх" и у нас 5 танков вверх поехали?
Вроде такой сценарий маловероятен.

2023-10-08 11:44 UTC, iagoshkov commented on src/main/java/ru/mipt/bit/platformer/action/MoveAction.java
> +        Movable movableGameEntity = (Movable) gameEntity;
Вообще в данном случае - не очень нормально.
А кто дает гарантию, что этот cast всегда сработает?
А что, если там окажется не Movable и у нас выбросится исключение ClassCastException?

2023-10-08 11:44 UTC, iagoshkov commented on src/main/java/ru/mipt/bit/platformer/action/MoveFactory.java
> +public class MoveFactory implements ActionFactory{
Мне кажется нет смысла в этом отдельно классе, он просто создает объект через new? Думаю достаточно иметь метод для этого в том классе, где вы хотите их создавать.

2023-10-08 11:44 UTC, iagoshkov commented on src/main/java/ru/mipt/bit/platformer/gameEntities/Level.java
> +    public boolean collidesExist(GridPoint2 coordinates) {
Ну, в принципе, это нормально иметь частью контракта класса Level возможность спросить у него все объекты, которые есть в уровне. Я бы не сказал, что это нарушение инкапсуляции.

2023-10-08 11:44 UTC, iagoshkov commented on src/main/java/ru/mipt/bit/test/LevelTest.java
> +        level.addGameEntity(mockedTank);
При этом у вас уже в уровне есть объекты из setUp. Но они никак не используются в тестах. 
Это не очень хорошо. Лучше прям тут создать тогда новый level и все, а не переиспользовать тот из секции setUp раз вам из него ничего не нужно.

2023-10-08 11:44 UTC, iagoshkov commented on src/main/java/ru/mipt/bit/test/MoveActionTest.java
> +        GridPoint2 targetCoordinates = direction.applyCoordinates(tank.getCurrentCoordinates());
Вот тут непонятно – эту строчку можно перенести и поставить после
moveAction.apply(tank)?
Если да – ее нужно туда перенести, чтобы было понятно, что относится к setup секции, а что – только к валидации. Иначе сложно читать и понимать это все вперемешку.

2023-10-08 11:44 UTC, iagoshkov commented on src/main/java/ru/mipt/bit/test/MoveActionTest.java
> +        GridPoint2 targetCoordinates = direction.applyCoordinates(tank.getCurrentCoordinates());
Тоже самое про следующую строчку

2023-10-08 11:44 UTC, iagoshkov commented on src/main/java/ru/mipt/bit/test/MoveActionTest.java
> +    public void testMoveForTankWithCollision() {
Называть бы хорошо, что мы тестируем и что ожидаем?
testApplyingMoveActionWithCollisionDoesNotChangeTargetCoordinates например )
Если это вообще так, я так сходу не могу без долго вчитывания понять, какой сценарий тут проверяется.

2023-10-08 11:44 UTC, iagoshkov commented on src/main/java/ru/mipt/bit/test/MoveActionTest.java
> +        assertNotEquals(targetCoordinates, tank.getDestinationCoordinates());
В данном случае это не очень хорошо, проверять, что что-то чему-то не равно.
Лучше явно сказать, что tank.getDestinationCoordinates равно originalCoordinates (1,0).
Так читателю будет понятнее.

2023-10-08 11:44 UTC, iagoshkov commented on src/main/java/ru/mipt/bit/test/ObstacleTest.java
> +    void testStateDoesntChange() {
В таком тесте особо смысла нет. Можно и оставить конечно. Но можно было и не писать.

2023-10-08 11:44 UTC, iagoshkov commented on src/main/java/ru/mipt/bit/test/TankTest.java
> +        GridPoint2 targetCoordinates = direction.applyCoordinates(tank.getCurrentCoordinates());
Не помню, кажтеся не все разобралии на занятии, если успеем – еще вернемся к этому.

2023-10-08 20:18 UTC, AsakoKabe commented on src/main/java/ru/mipt/bit/platformer/GameDesktopLauncher.java
> +        HashMap<GameEntity, Action> actions = actionController.generateGameEntitiesActions();
В ActionController.generateGameEntitiesActions() преполагается будет AIController и такой вызов `gameEntitiesActions.putAll(aiController.generateAction());`, но надо какой-то общий интерфейс (`EntityActionController`) и хранить эти контроллеры в контейнере

2023-10-08 20:18 UTC, AsakoKabe commented on src/main/java/ru/mipt/bit/platformer/action/InputController.java
> +        gameEntities.add(gameEntity);
Планировал создавать `EntityActionController`, который будет имплементировать `InputController` и `AIController`. В AIController этот контейнер, как раз пригодится, а тут да, не нужен

2023-10-08 20:18 UTC, AsakoKabe commented on src/main/java/ru/mipt/bit/platformer/action/MoveAction.java
> +        Movable movableGameEntity = (Movable) gameEntity;
Тогда лучше в методу сразу принимать Movable, а кастовать лучше "снаружи"? 
И вопрос был в целом, нормально ли кастовать объекты в java

2023-10-08 20:18 UTC, AsakoKabe commented on src/main/java/ru/mipt/bit/platformer/action/MoveFactory.java
> +public class MoveFactory implements ActionFactory{
У меня тут возникли сложности в Java, я не смог реализовать это через метод, чтобы при нажатии клавиши создавался новый `MoveAction`. 
Создавать я их хочу в `InputController`, но тогда при появлении новых `Action` класс будет сильно разрастаться из-за этих методов.

2023-10-08 20:18 UTC, AsakoKabe commented on src/main/java/ru/mipt/bit/test/MoveActionTest.java
> +    public void testMoveForTankWithCollision() {
всегда пугали такие большие названия в Java, а в иной случай еще больше запутаешь другого человека(

2023-10-08 20:18 UTC, AsakoKabe commented on src/main/java/ru/mipt/bit/test/TankTest.java
> +        GridPoint2 targetCoordinates = direction.applyCoordinates(tank.getCurrentCoordinates());
Таймлайн был такой
1 версия -> ревью -> 2 версия -> занятие 
На занятии Вы показывали 1 версию

2023-10-08 23:15 UTC, iagoshkov commented on src/main/java/ru/mipt/bit/test/MoveActionTest.java
> +    public void testMoveForTankWithCollision() {
Ну это тестовый метод – это нормально и привычно. Но в принципе вместо имени метода можно использовать специальную аннотацию и описать тестируемый сценарий словами в ней.

2023-10-08 23:28 UTC, iagoshkov commented on src/main/java/ru/mipt/bit/platformer/action/MoveAction.java
> +        Movable movableGameEntity = (Movable) gameEntity;
Ну я не очень понимаю как тут можно сразу принимать Movable, у вас же контракт должен быть единый для всех Action-ов. Не только для тех, которые будут движением управлять. Но и для стрельбы или еще каких-то.

В целом, кастовать классы в java – это чаще всего признак какого-то "костыля" или нарушение LSP.
Но иногда это может быть и частью дизайна, и это вполне нормально. Когда проверяют, поддерживает ли какой-то класс какой-то специфический интерфейс (instanceof SomeInterface) и если он поддерживает его, то делают каст к нему и работают через этот интерфейс. Иногда просто не получается обойтись без этого.

2023-10-08 23:30 UTC, iagoshkov commented on src/main/java/ru/mipt/bit/platformer/action/MoveFactory.java
> +public class MoveFactory implements ActionFactory{
Ну в целом может так даже и хорошо, посмотрю еще завтра. Надо понять лягут ли туда какие-то новые Action-ы, но так на вскидку кажется, что да.

2023-10-08 23:32 UTC, iagoshkov commented on src/main/java/ru/mipt/bit/platformer/gameEntities/Obstacle.java
> +    public void updateState(float deltaTime) {
это ок

2023-11-13 09:54 UTC, merged