Hometask 5
AsakoKabe/tank-software-design pull request #5
Opened 2023-10-16 20:56 UTC by AsakoKabe

2023-10-17 07:48 UTC, AsakoKabe commented on src/main/java/ru/platformer/game/graphics/LevelGraphics.java
> +    public void onAddGameObject(GameObject gameObject) {
Не знаю, как это исправить. У меня `Level` в методе `addGameObject` принимает `GameObject`. В наблюдатель приходит также `GameObject`.
Но конструктор графики `TankGraphics` и `ObstacleGraphics` у меня разные, им нужные разные `GameObject` и разные параметры для отрисовки
(тянется еще с прошлого pr)

2023-10-17 21:30 UTC, iagoshkov requested changes

2023-10-17 21:30 UTC, iagoshkov commented on src/main/java/ru/platformer/game/model/levelGenerators/LevelGenerator.java
> +    private static void initAxis(Level level, int maxAxis1, int maxAxis2, boolean inverse) {
выглядит как "костыль", а если мы в будушем сделаем, что деревья могут стать "уничтожаемыми" от выстрелов танков, то мы сможем уничтожить границы уровня и выехать за него?

2023-10-17 21:30 UTC, iagoshkov commented on src/main/java/ru/platformer/game/model/levelGenerators/RandomLevelGenerator.java
> +        createAI(level);
А причем тут createAI?
Мы же просто создаем уровень, мы на этом уровне абстракции вообще не знаем, будет там AI управлять танками или не AI. Мы просто уровень создаем. Зачем нам здесь coupling на AI?

2023-10-17 21:30 UTC, iagoshkov commented on src/main/java/ru/platformer/game/graphics/LevelGraphics.java
> +    public void onAddGameObject(GameObject gameObject) {
Ну, например, можно использовать шаблон стратегия для создания объектов графики.

2023-10-17 21:30 UTC, iagoshkov commented on src/main/java/ru/platformer/game/entityControllers/PlayerController.java
> +    public void addGameObject(GameObject player){
Тут похоже на нарушение контракта EntityController – получается в каких-то реализациях вы реально "добавлять объект под управление Controller-а", а в каких-то "перезатираете старый объект" – это неконсистентно и это "бомба замедленного действия", которая приведет к багу рано или поздно.
Почему не сделать управляемые объекты параметрами конструктора, например?

2023-10-17 21:30 UTC, iagoshkov commented on src/main/java/ru/platformer/game/AIEvent.java
> +public enum AIEvent {
А нужен ли этот промежуточный класс?
Почему бы внутри AIController-а не генерировать сразу Action, а не сначала какую-то промежуточную сущность и вторым шагом из нее Action?
Сама по себе эта абстракция кажется пока не выглядит особо полезной. И сюда постоянно придется новые добавлять значения, когда мы захотим стрелять и т.п.

2023-10-21 12:17 UTC, AsakoKabe commented on src/main/java/ru/platformer/game/AIEvent.java
> +public enum AIEvent {
В моей логике `AIController` и другие `EntityController` - класс, который инициирует запуск действия (как обсуждали в телеграмме). И для того, чтобы условно замокать внешний сервис, от которого мы будем получается событие (для `PlayerController` -  это нажатие кнопки), я сделал этот класс, т. е. я думал, что библиотека со следующей работы будете генерировать нам AIEvent и мы с ним работаем. Сам `AIEvent`, как класс будет браться из этой библиотеки.

2023-10-21 12:20 UTC, AsakoKabe commented on src/main/java/ru/platformer/game/model/CollisionDetector.java
> +    public void addCoordinates(GridPoint2 gridPoint2){
Безопасно ли добавлять координаты откуда-то из вне? По идеи, если мы забудем удалить какие-то координаты, то появится невидимое препятствие на карте. Как это пофиксить, пока не придумал

2023-10-21 12:27 UTC, AsakoKabe commented on src/main/java/ru/platformer/game/model/CollisionDetector.java
> +    public void addCoordinates(GridPoint2 gridPoint2){
Изначально это сделал, чтобы хранить `destinationCoordinates` от `Tank`, потому что `GameObject` хранит только `currentCoordinates`

2023-11-13 09:54 UTC, merged